#!/usr/bin/env python3
"""What `uv sync --no-dev` leaves out of the image, from the lockfile.

Chapter 12 tells the reader to put `--no-dev` in the Dockerfile. That is
an assertion until somebody prices it, and pricing it does not need
Docker: uv.lock records every wheel's URL and its size in bytes, so the
runtime dependency set and the full one can both be totalled by reading
a committed file. No network, no container, and the same answer on every
machine -- which is what makes it safe to commit the result.

What this is NOT is experiment E7. E7 builds three images and measures
what they weigh and how long they take to start, and the shape of the
image dominates the dependency set in that answer. This measures one of
the three differences between the shapes, exactly, and says nothing about
the other two.

Two things to keep in mind when reading the number:

  * These are DOWNLOAD bytes. A wheel is a zip; what it unpacks to is
    larger, so the footprint `--no-dev` removes from an image is more
    than the figure here, not less.
  * The wheel chosen for each package is the one a linux/amd64 container
    on the default (not free-threaded) build of the pinned interpreter
    would install: a manylinux x86_64 wheel where there is one, the pure
    `-none-any` wheel otherwise, and the source distribution if a package
    ships no wheel at all. The rule is stated here rather than inferred,
    because a different rule gives a different number.

Run from code/:   uv run python measure/deps_weight.py
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path
from typing import Any

CODE = Path(__file__).resolve().parents[1]
LOCK = CODE / "uv.lock"
OUT = CODE.parent / "figures" / "values" / "ch12.tex"
MIB = 1024 * 1024


def load_packages() -> dict[str, dict[str, Any]]:
    data: dict[str, Any] = tomllib.loads(LOCK.read_text(encoding="utf8"))
    packages: list[dict[str, Any]] = data["package"]
    return {p["name"]: p for p in packages}


def closure(
    packages: dict[str, dict[str, Any]], seed: list[str]
) -> set[str]:
    """Every package reachable from `seed` through `dependencies`."""
    seen: set[str] = set()
    stack = list(seed)
    while stack:
        name = stack.pop()
        if name in seen or name not in packages:
            continue
        seen.add(name)
        for dep in packages[name].get("dependencies", []):
            stack.append(dep["name"])
    return seen


def wheel_size(package: dict[str, Any]) -> int:
    """The bytes a linux/amd64 CPython container would actually fetch."""
    platform_wheels: list[dict[str, Any]] = []
    pure_wheels: list[dict[str, Any]] = []
    for wheel in package.get("wheels", []):
        filename = str(wheel["url"]).rsplit("/", 1)[-1]
        if "cp314t" in filename:
            continue  # the free-threaded ABI is a different interpreter
        if "manylinux" in filename and "x86_64" in filename:
            if "i686" not in filename:
                platform_wheels.append(wheel)
        elif filename.endswith("-none-any.whl"):
            pure_wheels.append(wheel)
    for group in (platform_wheels, pure_wheels):
        # pip and uv both prefer the most specific compatible wheel, so a
        # package shipping both a platform wheel and a pure one installs
        # the platform one. mypy is the case in this lock: 2.6 MiB pure
        # against 14.5 MiB compiled, and the compiled one is what lands.
        if group:
            return max(int(w.get("size", 0)) for w in group)
    return int(package.get("sdist", {}).get("size", 0))


def main() -> int:
    packages = load_packages()
    root = packages["python-for-dotnet-engineers"]
    runtime = closure(
        packages, [d["name"] for d in root["dependencies"]]
    ) - {root["name"]}
    dev_seed = [d["name"] for d in root["dev-dependencies"]["dev"]]
    full = (runtime | closure(packages, dev_seed)) - {root["name"]}

    runtime_bytes = sum(wheel_size(packages[n]) for n in runtime)
    full_bytes = sum(wheel_size(packages[n]) for n in full)
    if runtime_bytes <= 0:
        raise SystemExit("no wheel sizes in uv.lock: has its format moved?")

    values = {
        "ch12.deps.runtime.count": str(len(runtime)),
        "ch12.deps.full.count": str(len(full)),
        "ch12.deps.dev.count": str(len(full) - len(runtime)),
        "ch12.deps.runtime.mib": f"{runtime_bytes / MIB:.1f}",
        "ch12.deps.full.mib": f"{full_bytes / MIB:.1f}",
        "ch12.deps.dev.mib": f"{(full_bytes - runtime_bytes) / MIB:.1f}",
        "ch12.deps.ratio": f"{full_bytes / runtime_bytes:.2f}",
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"% Generated by code/measure/{Path(__file__).name}"
             " --- do not edit."]
    lines += [f"\\pyval{{{k}}}{{{v}}}" for k, v in values.items()]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
    for key, value in values.items():
        print(f"  {key:28} {value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
