#!/usr/bin/env python3
"""Experiment E6: the N+1, counted from the engine's own echo.

Chapter 10 claims a handful of numbers: what the obvious loop costs, what
the eager loader costs, and what a commit costs when nobody asked it for
anything. None of them is typed into the chapter -- they are written here,
into figures/values/e06.tex, and the page references them.

The functions measured are the chapter's own listings, imported rather
than re-implemented, so the page and the measurement cannot drift into
disagreeing about what was run. The instrument is ch10/counting.py, which
counts each statement twice -- once through the engine event the echo is
emitted from, once through the echo's own log lines -- and refuses to
report a number the two disagree about.

The sweep is the half worth having. One pair of numbers says the eager
loader is cheaper on this database; sweeping the parent count says what
KIND of cheaper, and that is the only version of the claim that survives a
bigger one: 1 + N against 2, whatever N is. The shape is asserted rather
than the figures, so a change that broke it could not come back as a
smaller number.

Run from code/:   uv run python measure/e06_nplusone.py
"""

from __future__ import annotations

import sys
from pathlib import Path

CODE = Path(__file__).resolve().parents[1]
ROOT = CODE.parent
# The listings are scripts and import their siblings by bare name, which is
# what the reader typing `uv run python ch10/nplusone.py` gets. Putting the
# chapter's directory on the path is what lets this file run the code the
# page prints rather than a copy of it. pyright is told the same thing, in
# code/pyproject.toml's executionEnvironments.
sys.path.insert(0, str(CODE / "ch10"))

from counting import Selects  # noqa: E402
from expiry import rename_then_report  # noqa: E402
from model import (  # noqa: E402
    ROWS,
    Base,
    Incident,
    Service,
    seeded_engine,
)
from nplusone import (  # noqa: E402
    counted,
    total_minutes_eager,
    total_minutes_lazy,
)
from sqlalchemy import Engine, create_engine  # noqa: E402
from sqlalchemy.orm import Session  # noqa: E402

OUT = ROOT / "figures" / "values" / "e06.tex"
MID, WIDE = 20, 50


def wide_engine(services: int) -> Engine:
    """The chapter's model, with more parents than the chapter's rows."""
    engine = create_engine("sqlite://")
    Base.metadata.create_all(engine)
    with Session(engine) as session:
        for n in range(services):
            service = Service(name=f"svc-{n:03d}")
            service.incidents = [
                Incident(title=f"i-{n}-{k}", severity=1 + k, minutes=10 * k)
                for k in range(3)
            ]
            session.add(service)
        session.commit()
    return engine


def at(parents: int) -> tuple[int, int]:
    """(lazy SELECTs, selectinload SELECTs) for that many parent rows."""
    engine = wide_engine(parents)
    counts: list[int] = []
    for strategy in (total_minutes_lazy, total_minutes_eager):
        with Session(engine) as session, Selects(engine) as count:
            strategy(session)
        counts.append(count.count)
    return counts[0], counts[1]


def main() -> int:
    engine = seeded_engine()
    services = len({row[0] for row in ROWS})
    lazy, _ = counted(engine, "lazy")
    selectin, _ = counted(engine, "selectin")
    joined, _ = counted(engine, "joined")

    expired_rows, expired = rename_then_report(engine, expire=True)
    _, kept = rename_then_report(engine, expire=False)
    # The finding is the identity, not the figure: the cost of reading
    # back objects you already had is one statement per object.
    assert expired_rows == services, (expired_rows, services)
    assert expired == services, (expired, services)

    mid_lazy, mid_eager = at(MID)
    wide_lazy, wide_eager = at(WIDE)
    for parents, lazy_n, eager_n in (
        (services, lazy, selectin),
        (MID, mid_lazy, mid_eager),
        (WIDE, wide_lazy, wide_eager),
    ):
        assert lazy_n == parents + 1, (parents, lazy_n)
        assert eager_n == selectin, (parents, eager_n)

    values: dict[str, int] = {
        "e06.services": services,
        "e06.incidents": len(ROWS),
        "e06.lazy.selects": lazy,
        "e06.selectin.selects": selectin,
        "e06.joined.selects": joined,
        "e06.expire.selects": expired,
        "e06.expire.kept": kept,
        "e06.mid.parents": MID,
        "e06.mid.lazy": mid_lazy,
        "e06.wide.parents": WIDE,
        "e06.wide.lazy": wide_lazy,
    }
    lines = ["% Generated by code/measure/e06_nplusone.py --- do not edit."]
    for key, value in values.items():
        lines.append(f"\\pyval{{{key}}}{{{value}}}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
    for key, value in values.items():
        print(f"  {key:24} {value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
