#!/usr/bin/env python3
"""Experiment E7: what three Dockerfile shapes weigh, and how fast they start.

OFF BY DEFAULT. It builds container images, which needs a Docker daemon and
a reachable registry, and it takes minutes rather than seconds. Turn it on
deliberately:

    PYBOOK_E7=1 uv run python measure/e07_images.py

Everything else under measure/ runs on every build, so a script that
silently tried to build three images would turn a forty-second job into a
ten-minute one and fail on any machine without a daemon. The switch follows
the same convention as PYBOOK_SOLUTIONS and PYBOOK_STARTERS.

Method. The three shapes are ch12/Dockerfile.naive, ch12/Dockerfile.slim
and ch12/Dockerfile. They are built against the same generated context so
that all three install the SAME packages -- requirements.txt is exported
from uv.lock rather than written by hand -- because otherwise the
measurement moves two things at once and neither number means anything.
Size is read from the daemon; cold start is the wall time of `docker run`
with an entrypoint that imports the runtime dependencies, taken as the
median of several runs after a discarded warm-up, which is the shape the
sibling books' benchmarks settled on.

Not run when this chapter was written. The machine that builds this book
has a Docker daemon and no route to any registry: both Docker Hub's blob
CDN and GitHub's container blob store answer 403 to the egress proxy, so
no base image can be fetched and nothing can be built. Every claim about
image size and start-up in chapter 12 is therefore labelled as judgement,
and the table that would hold these numbers is empty on purpose.
"""

from __future__ import annotations

import json
import os
import shutil
import statistics
import subprocess
import sys
import time
from pathlib import Path

CODE = Path(__file__).resolve().parents[1]
OUT = CODE.parent / "figures" / "values" / "e07.tex"
MIB = 1024 * 1024
RUNS = 5

# The import a cold start pays for: the runtime dependency set, not the app.
PROBE = "import fastapi, pydantic, sqlalchemy, structlog"

SHAPES = {
    "naive": "Dockerfile.naive",
    "slim": "Dockerfile.slim",
    "multi": "Dockerfile",
}


def run(args: list[str], cwd: Path | None = None) -> str:
    result = subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, check=True
    )
    return result.stdout


def build_context(target: Path) -> None:
    """The same packages for all three shapes, from the one lockfile."""
    target.mkdir(parents=True, exist_ok=True)
    for name in ("pyproject.toml", "uv.lock"):
        shutil.copy2(CODE / name, target / name)
    shutil.copytree(CODE / "src", target / "src", dirs_exist_ok=True)
    for shape in SHAPES.values():
        shutil.copy2(CODE / "ch12" / shape, target / shape)
    requirements = run(
        ["uv", "export", "--no-dev", "--no-emit-project",
         "--format", "requirements.txt"],
        cwd=CODE,
    )
    (target / "requirements.txt").write_text(requirements, encoding="utf8")


def image_size_mib(tag: str) -> float:
    raw = run(["docker", "image", "inspect", tag, "--format", "{{.Size}}"])
    return int(raw.strip()) / MIB


def cold_start_ms(tag: str) -> float:
    timings: list[float] = []
    for attempt in range(RUNS + 1):
        start = time.perf_counter()
        run(["docker", "run", "--rm", "--entrypoint", "python",
             tag, "-c", PROBE])
        elapsed = (time.perf_counter() - start) * 1000
        if attempt:  # the first pulls nothing but still warms the cache
            timings.append(elapsed)
    return statistics.median(timings)


def main() -> int:
    if os.environ.get("PYBOOK_E7", "0") in ("0", ""):
        print("  e07: skipped. Set PYBOOK_E7=1, with a Docker daemon and")
        print("       a reachable registry, to build and measure.")
        return 0

    context = CODE.parent / "build" / "e07"
    build_context(context)
    values: dict[str, str] = {}
    for shape, dockerfile in SHAPES.items():
        tag = f"pybook-e07-{shape}"
        print(f"  building {shape} ...")
        run(["docker", "build", "-f", dockerfile, "-t", tag, "."],
            cwd=context)
        values[f"e07.{shape}.mib"] = f"{image_size_mib(tag):.0f}"
        values[f"e07.{shape}.ms"] = f"{cold_start_ms(tag):.0f}"

    naive = float(values["e07.naive.mib"])
    multi = float(values["e07.multi.mib"])
    values["e07.shrink"] = f"{naive / multi:.1f}"
    values["e07.runs"] = str(RUNS)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% Generated by code/measure/e07_images.py --- do not edit."]
    lines += [f"\\pyval{{{k}}}{{{v}}}" for k, v in sorted(values.items())]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
    print(json.dumps(values, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
