#!/usr/bin/env python3
"""Count every ledger Appendix E prints, out of the tree, into a value file.

Appendix E is generated rather than written. It prints how many chapters are
stubs, how many listings and exercises exist, how many listings still carry a
verifybox, and how many diagrams each edition has -- and an appendix of
hand-typed counts is exactly the artefact that goes stale in weeks with
nothing able to see it. So this script counts, writes
figures/values/ledgers.tex, and `make verify` fails when the tree moves and
the committed file does not.

Two rules the script holds itself to, both learned in the sibling books:

  * Every count is PER EDITION, because that is what a reader holds, and the
    two editions are asserted equal here so that a stub in one and not the
    other stops the build rather than printing a number that is true of
    neither copy.
  * It copies the arithmetic of the tools that print the same quantities
    (tools/check_structure.py, `make debt`) rather than re-deriving the
    definition, because two implementations that agree on a definition and
    differ on an edge case is how a ledger starts lying.

Run from code/:   uv run python measure/ledgers.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "figures" / "values" / "ledgers.tex"

RE_STUB = re.compile(r"\\chapterstub\{")
RE_VERIFY = re.compile(r"\\begin\{verifybox\}")
RE_EXERCISE = re.compile(r"\\begin\{exercise\}\{([^}]*)\}")


def tex_files(tree: str, lang: str) -> list[Path]:
    return sorted((ROOT / tree / lang).glob("*.tex"))


def count_stubs(tree: str, lang: str) -> int:
    return sum(
        1 for p in tex_files(tree, lang)
        if RE_STUB.search(p.read_text(encoding="utf8"))
    )


def count_re(pattern: re.Pattern[str], trees: list[str], lang: str) -> int:
    n = 0
    for tree in trees:
        for p in tex_files(tree, lang):
            n += len(pattern.findall(p.read_text(encoding="utf8")))
    return n


def same(name: str, en: int, pl: int) -> int:
    if en != pl:
        raise SystemExit(
            f"{name}: the two editions disagree (en={en}, pl={pl}); "
            f"a reader of one copy would be told a number true of neither"
        )
    return en


def main() -> int:
    manifest = json.loads(
        (ROOT / "tools" / "chapters.json").read_text(encoding="utf8")
    )
    chapters_total = len(manifest["chapters"])
    appendices_total = len(manifest["appendices"])

    chapter_stubs = same(
        "chapter stubs",
        count_stubs("chapters", "en"),
        count_stubs("chapters", "pl"),
    )
    appendix_stubs = same(
        "appendix stubs",
        count_stubs("appendices", "en"),
        count_stubs("appendices", "pl"),
    )
    verify = same(
        "verifybox",
        count_re(RE_VERIFY, ["chapters", "appendices"], "en"),
        count_re(RE_VERIFY, ["chapters", "appendices"], "pl"),
    )
    exercises = same(
        "exercises",
        count_re(RE_EXERCISE, ["frontmatter", "chapters", "appendices"], "en"),
        count_re(RE_EXERCISE, ["frontmatter", "chapters", "appendices"], "pl"),
    )
    diagrams = same(
        "diagrams",
        len(list((ROOT / "figures" / "mermaid" / "en").glob("*.mmd"))),
        len(list((ROOT / "figures" / "mermaid" / "pl").glob("*.mmd"))),
    )
    code = ROOT / "code"
    listings = sum(
        1
        for d in sorted(code.glob("ch[0-9][0-9]"))
        for p in d.glob("*.py")
        if not p.name.startswith("_")
    )

    values = {
        "ledger.chapters.total": chapters_total,
        "ledger.chapters.written": chapters_total - chapter_stubs,
        "ledger.chapters.stubs": chapter_stubs,
        "ledger.appendices.total": appendices_total,
        "ledger.appendices.stubs": appendix_stubs,
        "ledger.verifybox": verify,
        "ledger.exercises": exercises,
        "ledger.listings": listings,
        "ledger.diagrams": diagrams,
    }
    lines = ["% Generated by code/measure/ledgers.py --- do not edit."]
    for key, value in values.items():
        lines.append(f"\\pyval{{{key}}}{{{value}}}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
    for key, value in values.items():
        print(f"  {key:32} {value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
