#!/usr/bin/env python3
"""What the guiding project's own suite costs, and how big it is.

Three numbers reach Chapter 14 from here, and one of them is a bound rather
than a figure.

  * The assertion count is READ FROM THE PACKAGE, never typed. If the
    twelve ever became thirteen, the page would follow the package rather
    than disagreeing with it.
  * The test count is read from pytest's own collection, for the same
    reason.
  * The suite's run time is a property of THIS machine, so committing the
    seconds it took here would be committing a number no reader and no CI
    runner can reproduce -- and `make verify` would go red on every run,
    which is how a drift gate teaches people to ignore it. What is
    committed is a CEILING the run has to clear, and the script fails if
    it does not. The claim the book then makes is one that survives being
    checked on somebody else's laptop.

Run from code/:   uv run python measure/trace_assert.py
"""

from __future__ import annotations

import re
import subprocess
import sys
import time
from pathlib import Path

CODE = Path(__file__).resolve().parents[1]
OUT = CODE.parent / "figures" / "values" / "trace-assert.tex"

# Measured before it was chosen: the whole run, interpreter start
# included, takes about half a second on the machine the book is built on.
# Five seconds is an order above that -- room for a cold import on a loaded
# CI runner -- and still small enough that the sentence it supports means
# something. A ceiling is swept, not guessed, and then it is a bound.
CEILING_SECONDS = 5

RE_PASSED = re.compile(r"\b(\d+) passed\b")


def timed_run() -> tuple[int, float]:
    """One run, timed, and its own count of tests read back from it.

    Not `--collect-only`, and that is worth a sentence: pytest 9 prints a
    per-FILE count there (`tests/test_trace_assert.py: 18`) where pytest 8
    printed one node id per line, so the obvious way to count -- one line
    per collected test -- silently returns zero. It did, on the first run
    of this script. The summary line is the stable thing to parse, and it
    comes from a run rather than from a collection, which is the number the
    reader would get.

    `-o addopts=` clears the project's own `-q` first, because a second
    `-q` on top of it is not more of the same: pytest reads the pair as
    "quieter still" and drops the summary line this parses. The first
    version of this script asked for `-q` and got no summary at all.
    """
    started = time.perf_counter()
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "-o", "addopts=", "-q",
         "tests/test_trace_assert.py"],
        cwd=CODE,
        capture_output=True,
        text=True,
        check=True,
    )
    elapsed = time.perf_counter() - started
    found = RE_PASSED.search(result.stdout)
    if not found:
        raise SystemExit(f"no 'N passed' in pytest output:\n{result.stdout}")
    return int(found.group(1)), elapsed


def main() -> int:
    sys.path.insert(0, str(CODE / "src"))
    from trace_assert import ASSERTIONS  # noqa: PLC0415

    tests, elapsed = timed_run()
    if elapsed >= CEILING_SECONDS:
        raise SystemExit(
            f"the suite took {elapsed:.3f}s, which is not under the "
            f"committed ceiling of {CEILING_SECONDS}s. Either the suite "
            f"has grown something slow, or the ceiling is wrong -- and "
            f"the page says 'under {CEILING_SECONDS} seconds'."
        )

    values = {
        "ta.assertions": len(ASSERTIONS),
        "ta.tests": tests,
        "ta.ceiling": CEILING_SECONDS,
    }
    lines = ["% Generated by code/measure/trace_assert.py --- do not edit."]
    for key, value in values.items():
        lines.append(f"\\pyval{{{key}}}{{{value}}}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
    for key, value in values.items():
        print(f"  {key:20} {value}")
    print(f"  (the run took {elapsed:.3f}s, under the {CEILING_SECONDS}s "
          f"ceiling; the seconds are not committed, the ceiling is)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
