.PHONY: all en pl check numbers verify diagrams diagrams-clean code starters \
        stubs stubs-check listings exercises transcripts lines pins words csbox \
        translate shots debt site watch-en watch-pl clean

# One paper format, two languages. The book is read on a screen with an editor
# beside it, so there is no trade format and no A4-versus-something choice:
# main-en.tex and main-pl.tex differ in two lines and share everything else.
LANGS := en pl

UV ?= uv
MMD_SRC := $(wildcard figures/mermaid/en/*.mmd) $(wildcard figures/mermaid/pl/*.mmd)
MMD_PDF := $(patsubst figures/mermaid/%.mmd,figures/diagrams/%.pdf,$(MMD_SRC))

# Everything a script under code/measure/ writes and git tracks. The book's
# promise -- that the page cannot disagree with the script that computed it --
# is exactly as wide as this variable and no wider, so anything a script emits
# belongs in it.
COMPUTED := figures/values figures/transcripts

# mermaid-cli drives a headless Chromium. The config below is written on first
# use and points at whatever browser is available; override BROWSER on the
# command line if yours lives somewhere else.
BROWSER ?= $(shell command -v chromium 2>/dev/null || command -v chromium-browser 2>/dev/null || command -v google-chrome 2>/dev/null || echo /opt/pw-browsers/chromium)

all: numbers diagrams en pl check

# The gates. A build that only *looked* like it succeeded is the failure mode
# this book cannot afford: -interaction=nonstopmode writes a PDF over the top
# of an error, and with -file-line-error the error line does not begin with a
# `!`, so the inherited `grep '^!' main.log` habit cannot see it.
#
# The SOURCE gates come first and need no PDF. Run them before a build, not
# after: they cost seconds against a build that costs minutes.
# parity.py is NOT piped into tail. A pipeline's exit status is the LAST
# command's, so `parity.py | tail -n 3` could not fail this target however
# many checks failed -- the gate the whole bilingual design rests on was
# advisory in the one place a person runs it. The output is captured instead:
# the summary on success, everything on failure.
check:
	@python3 tools/gen_stubs.py --check
	@out=$$(python3 tools/parity.py) || { echo "$$out"; exit 1; }; \
	 echo "$$out" | tail -n 3
	@python3 tools/check_structure.py --listings
	@python3 tools/check_structure.py --exercises
	@python3 tools/check_structure.py --transcripts
	@python3 tools/check_structure.py --lines
	@python3 tools/check_structure.py --pins
	@python3 tools/check_structure.py --words
	@python3 tools/checklog.py main-en.log main-pl.log
	@# reflist needs both aux trees, so it is skipped -- and says so -- on a
	@# tree without a build, and is a hard failure on one with a build.
	@if [ -f main-en.aux ] && [ -f main-pl.aux ]; then python3 tools/reflist.py; \
	 else echo "  (cross-reference comparison skipped: build both editions first)"; fi

en: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-en.tex
	@python3 tools/checklog.py main-en.log

pl: numbers
	latexmk -pdf -interaction=nonstopmode -file-line-error main-pl.tex
	@python3 tools/checklog.py main-pl.log

watch-en:
	latexmk -pvc -pdf -interaction=nonstopmode main-en.tex
watch-pl:
	latexmk -pvc -pdf -interaction=nonstopmode main-pl.tex

clean:
	for j in main-en main-pl; do latexmk -C $$j.tex; done
	rm -rf _site
	rm -f *.dgm *.exr *.ilg *.ind *.idx chapters/*/*.aux appendices/*/*.aux

# ---------------------------------------------------------------------------
# The code. Every listing, exercise and measurement is one uv project under
# code/, locked to the versions on the title page. This is what CI runs.
# ---------------------------------------------------------------------------
code:
	cd code && $(UV) sync --locked
	cd code && $(UV) run ruff check .
	cd code && $(UV) run pyright
	cd code && PYBOOK_SOLUTIONS=1 $(UV) run pytest

# Every exercise STARTER must still fail its test: an exercise whose starter
# already passes is not an exercise. conftest.py marks every exercise test as
# a strict expected failure under this variable, so an unexpected pass fails.
starters:
	cd code && PYBOOK_STARTERS=fail $(UV) run pytest exercises

# ---------------------------------------------------------------------------
# Numbers. Every measured value and every quoted program output is produced
# here and pulled into the text with \val{} or \transcript{}. The book does
# not contain the digits, it contains a reference to them.
# ---------------------------------------------------------------------------
numbers:
	@mkdir -p $(COMPUTED)
	@cd code && for f in measure/*.py; do \
	  echo "  measure: $$f"; \
	  $(UV) run python "$$f" || exit 1; \
	done
	@# One file the preamble can \input, because TeX cannot glob a directory.
	@{ echo '% Generated by `make numbers` --- do not edit.'; \
	   for v in figures/values/*.tex; do \
	     case "$$v" in */all.tex) continue;; esac; \
	     echo "\\input{$${v%.tex}}"; \
	   done; } > figures/values/all.tex
	@echo "  index:   figures/values/all.tex"

# Re-runs the scripts and fails if any committed value would change. TWO
# failures, not one, and `git diff` alone can only see the first: drift in a
# tracked file, and a file git has never seen, which has therefore never been
# compared to anything. Staged-but-not-committed is NOT a failure: the content
# matches the script, which is the whole question this gate asks.
verify: numbers
	@drift=$$(git diff --name-only -- $(COMPUTED)); \
	 new=$$(git ls-files --others --exclude-standard -- $(COMPUTED)); \
	 if [ -n "$$drift" ] || [ -n "$$new" ]; then \
	   [ -n "$$drift" ] && { echo "STALE: these no longer match their script:"; \
	                         echo "$$drift"; git diff --stat -- $(COMPUTED); }; \
	   [ -n "$$new" ] && { echo "UNTRACKED: git has never seen these, so they have"; \
	                       echo "never been compared to anything. git add them:"; \
	                       echo "$$new"; }; \
	   exit 1; \
	 else echo "All computed output is current: values and transcripts."; fi

# ---------------------------------------------------------------------------
# Diagrams. Source of truth is figures/mermaid/<lang>/*.mmd, committed. The
# rendered PDFs are build output and are gitignored.
# ---------------------------------------------------------------------------
diagrams: $(MMD_PDF)

figures/diagrams/%.pdf: figures/mermaid/%.mmd figures/mermaid/.puppeteer.json figures/mermaid/config.json
	@mkdir -p $(dir $@)
	npx -y @mermaid-js/mermaid-cli@11 \
	  -i $< -o $@ \
	  -p figures/mermaid/.puppeteer.json \
	  -c figures/mermaid/config.json \
	  -b transparent --pdfFit

figures/mermaid/.puppeteer.json:
	@mkdir -p figures/mermaid
	@printf '{"executablePath":"%s","args":["--no-sandbox","--disable-dev-shm-usage"]}\n' "$(BROWSER)" > $@
	@echo "Wrote $@ pointing at $(BROWSER)"

diagrams-clean:
	rm -rf figures/diagrams

# ---------------------------------------------------------------------------
# Debt ledgers. Each is a promise made to a reader that has not yet been kept,
# so it is counted rather than remembered.
# ---------------------------------------------------------------------------
stubs-check:
	@python3 tools/gen_stubs.py --check

stubs:
	@python3 tools/check_structure.py --stubs --soft

listings:
	@python3 tools/check_structure.py --listings

exercises:
	@python3 tools/check_structure.py --exercises

transcripts:
	@python3 tools/check_structure.py --transcripts

lines:
	@python3 tools/check_structure.py --lines

pins:
	@python3 tools/check_structure.py --pins

words:
	@python3 tools/check_structure.py --words --soft

csbox:
	@python3 tools/check_structure.py --csbox

translate:
	@out=$$(python3 tools/parity.py) || { echo "$$out"; exit 1; }; \
	 echo "$$out" | tail -n 3
	@if [ -f main-en.aux ] && [ -f main-pl.aux ]; then python3 tools/reflist.py; \
	 else echo "  (cross-reference comparison skipped: build both editions first)"; fi

shots:
	@printf "  verifybox blocks: "
	@grep -rc 'begin{verifybox}' chapters appendices 2>/dev/null \
	  | awk -F: '{s+=$$2} END {print s+0}'
	@printf "  mermaid sources:  "
	@ls figures/mermaid/*/*.mmd 2>/dev/null | wc -l

debt:
	@echo "== Manifest and tree =="              ; $(MAKE) -s stubs-check || true
	@echo; echo "== Chapters not yet written ==" ; $(MAKE) -s stubs
	@echo; echo "== Listings on the page =="     ; $(MAKE) -s listings || true
	@echo; echo "== Exercises with a test =="    ; $(MAKE) -s exercises || true
	@echo; echo "== Transcripts on the page =="  ; $(MAKE) -s transcripts || true
	@echo; echo "== 79 columns =="               ; $(MAKE) -s lines || true
	@echo; echo "== Pins in step =="             ; $(MAKE) -s pins || true
	@echo; echo "== Word budgets =="             ; $(MAKE) -s words
	@echo; echo "== Translation boxes =="        ; $(MAKE) -s csbox
	@echo; echo "== Polish/English parity =="    ; $(MAKE) -s translate
	@echo; echo "== Unverified listings, diagrams =="; $(MAKE) -s shots

# Assemble locally exactly what CI publishes to Pages.
site: en pl
	@rm -rf _site && mkdir -p _site
	@cp -r docs/. _site/
	@cp main-en.pdf "_site/Python-for-dotNET-Engineers.pdf"
	@cp main-pl.pdf "_site/Python-dla-inzynierow-dotNET.pdf"
	@cp main-en.pdf _site/book-en.pdf
	@cp main-pl.pdf _site/book-pl.pdf
	@echo "  _site/ assembled. Open _site/index.html."
