"""What Alembic's autogenerate actually computes, without an alembic.ini.

`alembic revision --autogenerate` is two steps: diff the models against the
live database, then write the diff out as a migration script. This runs the
first step directly -- the same function the command calls -- against a
database whose only difference from the models is that one column has been
renamed.

A rename is not in the answer. It cannot be: the diff sees a column that is
gone and a column that is new, and no amount of reading the models tells it
they are the same column. Applied as generated, that migration drops the
data and creates an empty column beside it.

Run it from code/:

    uv run python ch10/autogenerate.py
"""

from __future__ import annotations

from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from sqlalchemy import Engine, create_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# --8<-- [start:models]


class Shipped(DeclarativeBase):
    """What the database has, because a migration built it."""


class ServiceV1(Shipped):
    __tablename__ = "service"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]


class Proposed(DeclarativeBase):
    """What the models say now: one column, renamed."""


class ServiceV2(Proposed):
    __tablename__ = "service"
    id: Mapped[int] = mapped_column(primary_key=True)
    display_name: Mapped[str]


# --8<-- [end:models]

# --8<-- [start:diff]


def autogenerated(engine: Engine) -> list[str]:
    """The operations `--autogenerate` would write into the migration."""
    with engine.connect() as connection:
        context = MigrationContext.configure(connection)
        diff = compare_metadata(context, Proposed.metadata)
    return [str(op[0]) for op in diff]


# --8<-- [end:diff]


def main() -> int:
    engine = create_engine("sqlite://")
    Shipped.metadata.create_all(engine)
    operations = autogenerated(engine)
    print(f"one column renamed, autogenerate says: {', '.join(operations)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
