flowchart LR
    D["Definition time:<br/>the def statement<br/>has just finished"] --> A["The decorator is CALLED,<br/>handed the function object,<br/>and returns something else"]
    A --> N["The name now refers to<br/>whatever it returned.<br/>An attribute would have<br/>changed nothing at all here"]
