#!/usr/bin/env python3
"""Regenerate the chapter and appendix stubs and the two structure files from
tools/chapters.json.

The manifest is the single source of the part and chapter sequence, so a change
to the plan -- inserting a chapter, moving one between parts, rewriting a brief
-- is one edit there and one run of this script, rather than thirty-six edits
made by hand and a renumbering done by eye.

It will NEVER overwrite a chapter that has been written. A file that no longer
carries a \\chapterstub{} is finished prose and is left exactly alone; if such a
chapter has been renumbered or dropped from the manifest, the script says so and
stops, because moving written work is a decision and not a side effect.

Run:  python3 tools/gen_stubs.py            (from the repository root)
      python3 tools/gen_stubs.py --check    (fail if anything is out of date)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]

EN_STUB = """%% {key} --- {en}
%%
%% Stub, generated by tools/gen_stubs.py from tools/chapters.json.
%% The brief below is the contract for this chapter: what it must argue, what
%% it must buy the reader, and what it must NOT repeat from the companion
%% volumes. Writing the chapter means deleting the \\chapterstub{{}} block and
%% replacing it with the chapter -- after which this file is never regenerated.
%% If the brief turns out to be wrong once the code has been run, change it in
%% the manifest and record the contradiction in CLAUDE.md under *Resolved
%% questions*.

\\chapter{{{en}}}
\\label{{{label}}}

\\chapterstub{{%
{brief}
{tail}}}
"""

PL_STUB = """%% {key} --- {pl}
%%
%% Zalążek, wygenerowany przez tools/gen_stubs.py z tools/chapters.json.
%% Poniższy opis jest kontraktem tego rozdziału: co ma uzasadnić, co ma dać
%% czytelnikowi i czego NIE ma powtarzać za tomami towarzyszącymi. Napisanie
%% rozdziału oznacza usunięcie bloku \\chapterstub{{}} i zastąpienie go
%% rozdziałem -- po czym ten plik nie jest już generowany.

\\chapter{{{pl}}}
\\label{{{label}}}

\\chapterstub{{%
\\textit{{[Opis do przetłumaczenia --- patrz wydanie angielskie.]}}

{brief}
{tail}}}
"""

STRUCTURE_HEAD = r"""% ============================================================
%  structure.tex --- the part and chapter sequence
%
%  GENERATED by tools/gen_stubs.py from tools/chapters.json. Edit the manifest,
%  not this file.
%
%  Shared by both editions. There is exactly one list of chapters in this
%  repository, and both main files read it through body.tex, so the Polish and
%  English editions cannot contain different chapters. A chapter added here
%  appears in both, or fails the build in whichever language has not been
%  written.
% ============================================================

\newcommand{\includechapter}[1]{\include{chapters/\booklang/#1}}
"""

APPENDIX_HEAD = r"""% ============================================================
%  structure-appendices.tex --- the appendix sequence
%
%  GENERATED by tools/gen_stubs.py from tools/chapters.json. Edit the manifest,
%  not this file. body.tex issues \appendix and the part title before reading
%  this, so the file carries the includes and nothing else.
% ============================================================

\newcommand{\includeappendix}[1]{\include{appendices/\booklang/#1}}
"""


def title(s: str) -> str:
    """A chapter title is prose that also becomes a PDF bookmark and a
    contents line, so it may carry no raw TeX special. `#` is the one a
    C# book cannot avoid: raw, it breaks hyperref's title capture with
    `Illegal parameter number in definition of \\GetTitleStringResult`
    at the \\chapter line, which names neither the character nor the
    cause. \\# is robust in all three places."""
    for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_")):
        s = s.replace(a, b)
    return s


def latexify(s: str) -> str:
    """Turn a brief written as prose into LaTeX that compiles.

    `x` becomes \\code{x}, with underscores escaped. Anything inside backticks
    that carries an exponent becomes maths, because \\code{n^2} is a missing
    dollar. This ran as a one-off patch once in a sibling repository and the next
    regeneration undid it, which is why it lives here.
    """
    s = re.sub(r"`([^`]*)`", lambda m: r"\code{" + m.group(1) + "}", s)

    def fix(m: re.Match) -> str:
        body = m.group(1)
        if re.search(r"\^", body):
            body = re.sub(r"\^(\w+)", r"^{\1}", body)
            return "$" + body + "$"
        body = body.replace("_", r"\_").replace("#", r"\#").replace("%", r"\%")
        body = body.replace("&", r"\&").replace("~", r"\textasciitilde{}")
        return r"\code{" + body + "}"

    def prose(seg: str) -> str:
        # Prose only: the quote and dash rewrites used to run over the whole
        # string AFTER the \code{} conversion, so a brief carrying
        # `if __name__ == "__main__"` got \enquote{} inside its \code{} and
        # printed curly quotes in a code span.
        for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_")):
            seg = seg.replace(a, b)
        seg = re.sub(r'"([^"]{1,200}?)"',
                     lambda m: r"\enquote{" + " ".join(m.group(1).split()) + "}",
                     seg, flags=re.S)
        return re.sub(r"(?<!-)-- ", r"\\dash{} ", seg)

    out, last = [], 0
    for m in re.finditer(r"\\code\{([^{}]*)\}", s):
        out.append(prose(s[last:m.start()]))
        out.append(fix(m))
        last = m.end()
    out.append(prose(s[last:]))
    return "".join(out)


def check_brief(pid: str, brief: str) -> list[str]:
    """A bare ^ in a brief is a fatal build error, and it is silent here.

    latexify() turns an exponent into maths only INSIDE backticks; outside them
    a caret reaches LaTeX raw, opens maths mode and swallows the rest of the
    paragraph. Refusing is better than escaping it, because a caret in a brief
    always MEANS an exponent, so the author wants backticks.
    """
    problems = []
    outside = re.sub(r"`[^`]*`", "", brief)
    if "^" in outside:
        problems.append(f"{pid}: bare caret outside backticks; write it as `x^2`")
    if "\\" in brief:
        problems.append(f"{pid}: a backslash in a brief reaches LaTeX raw; "
                        f"write prose and backticks only")
    if "{" in brief or "}" in brief:
        problems.append(f"{pid}: braces in a brief unbalance the stub; "
                        f"describe the construct in words")
    return problems


def wrap(s: str, width: int = 76) -> str:
    return "\n\n".join(textwrap.fill(p, width) for p in s.split("\n\n"))


def written(path: Path) -> bool:
    return path.is_file() and "\\chapterstub{" not in path.read_text(encoding="utf8")


def tail_for(entry: dict, lang: str) -> str:
    """The planning figures a stub prints under its brief."""
    lines = []
    if "words" in entry:
        lab = "Word budget" if lang == "en" else "Budżet słów"
        lines.append(f"\\textbf{{{lab}:}} {entry['words']}.")
    if entry.get("release"):
        lab = "Ships in" if lang == "en" else "Wydanie"
        lines.append(f"\\textbf{{{lab}:}} {entry['release']}.")
    if entry.get("experiment"):
        lab = "Measurement" if lang == "en" else "Pomiar"
        lines.append(f"\\textbf{{{lab}:}} {entry['experiment']}.")
    if entry.get("stage"):
        lab = "Guiding project" if lang == "en" else "Projekt przewodni"
        lines.append(f"\\textbf{{{lab}:}} {latexify(entry['stage'])}.")
    if not lines:
        return ""
    return "\n\\medskip\n" + "\\\\\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report what would change and exit non-zero, writing nothing")
    a = ap.parse_args()

    m = json.loads((ROOT / "tools" / "chapters.json").read_text(encoding="utf8"))
    chapters, parts, appendices = m["chapters"], m["parts"], m["appendices"]
    byid = {c["id"]: c for c in chapters}

    # Every chapter is in exactly one part, in manifest order.
    placed = [i for p in parts for i in p["ids"]]
    if placed != [c["id"] for c in chapters]:
        print("  MANIFEST: the parts do not list every chapter exactly once, in order:")
        print(f"    parts:    {placed}")
        print(f"    chapters: {[c['id'] for c in chapters]}")
        return 1

    bad = [msg for e in chapters + appendices for msg in check_brief(e["key"], e["brief"])]
    if bad:
        print("  BRIEF WILL NOT COMPILE:")
        for msg in bad:
            print("    " + msg)
        return 1

    changed: list[str] = []
    plan = [("chapters", chapters), ("appendices", appendices)]

    # A written file whose name is no longer in the manifest has been
    # renumbered or dropped under it. That is a decision, not a side effect.
    for tree, entries in plan:
        wanted = {e["file"] + ".tex" for e in entries}
        for lang in ("en", "pl"):
            for f in sorted((ROOT / tree / lang).glob("*.tex")):
                if f.name not in wanted and written(f):
                    print(f"  REFUSING: {f.relative_to(ROOT)} is written and the "
                          f"manifest no longer lists it. Rename it deliberately, "
                          f"then re-run.")
                    return 2
        for lang in ("en", "pl"):
            for f in sorted((ROOT / tree / lang).glob("*.tex")):
                if f.name not in wanted:
                    changed.append(f"delete {f.relative_to(ROOT)}")
                    if not a.check:
                        f.unlink()

    for tree, entries in plan:
        for e in entries:
            brief = wrap(latexify(e["brief"]))
            for lang, tmpl in (("en", EN_STUB), ("pl", PL_STUB)):
                path = ROOT / tree / lang / (e["file"] + ".tex")
                if written(path):
                    continue
                body = tmpl.format(key=e["key"], en=title(e.get("en", "")),
                                   pl=title(e.get("pl", "")),
                                   label=e["label"], brief=brief,
                                   tail=tail_for(e, lang))
                if not path.is_file() or path.read_text(encoding="utf8") != body:
                    changed.append(f"write {path.relative_to(ROOT)}")
                    if not a.check:
                        path.parent.mkdir(parents=True, exist_ok=True)
                        path.write_text(body, encoding="utf8")

    out = [STRUCTURE_HEAD]
    for i, part in enumerate(parts):
        out.append("\n\\part{\\lblPart%s}\n" % ROMAN[i])
        for cid in part["ids"]:
            out.append("\\includechapter{%s}\n" % byid[cid]["file"])
    text = "".join(out)
    sp = ROOT / "structure.tex"
    if not sp.is_file() or sp.read_text(encoding="utf8") != text:
        changed.append("write structure.tex")
        if not a.check:
            sp.write_text(text, encoding="utf8")

    out = [APPENDIX_HEAD, "\n"]
    for e in appendices:
        out.append("\\includeappendix{%s}\n" % e["file"])
    text = "".join(out)
    sp = ROOT / "structure-appendices.tex"
    if not sp.is_file() or sp.read_text(encoding="utf8") != text:
        changed.append("write structure-appendices.tex")
        if not a.check:
            sp.write_text(text, encoding="utf8")

    if a.check:
        for c in changed:
            print(f"  OUT OF DATE: {c}")
        if not changed:
            print(f"  {len(chapters)} chapters in {len(parts)} parts, "
                  f"{len(appendices)} appendices; stubs and structure are current.")
        return 1 if changed else 0

    print(f"  {len(chapters)} chapters in {len(parts)} parts, {len(appendices)} "
          f"appendices; {len(changed)} file(s) written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
